config/routes.rb
Open311Router::Application.routes.draw do
  
  match 'discovery' => 'discovery#index'
  
  resources :end_points

  root :to => 'discovery#index'

end

app/models/end_point.rb
class EndPoint < ActiveRecord::Base
  attr_accessible :change_set, :environment, :specification, :url
  
  Except_List = [:created_at, :updated_at, :server_id, :id]
  
  def as_json(options={})
    super(:except => Except_List)
  end
  
  def to_xml(options={})
    options.merge!(:except => Except_List)
    super(options)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/discovery_controller.rb
class DiscoveryController < ApplicationController
  # GET /discovery
  # GET /discovery.json
  def index
    @end_points = EndPoint.all
    
    @discovery = {
      changeset: "v1",
      contact: "contact@seeclickfix.com",
      key_service: "No keys needed at this point",
      endpoints: @end_points
    }
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @discovery }
      format.xml { render xml: @discovery.to_xml(:root => 'discovery', :skip_types => true, :skip_instruct => true, :indent => 2) }
    end
  end


end

app/controllers/end_points_controller.rb
class EndPointsController < ApplicationController
  # GET /end_points
  # GET /end_points.json
  def index
    @end_points = EndPoint.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @end_points }
    end
  end

  # GET /end_points/1
  # GET /end_points/1.json
  def show
    @end_point = EndPoint.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @end_point }
      format.xml { render xml: @end_point }
    end
  end

  # GET /end_points/new
  # GET /end_points/new.json
  def new
    @end_point = EndPoint.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @end_point }
    end
  end

  # GET /end_points/1/edit
  def edit
    @end_point = EndPoint.find(params[:id])
  end

  # POST /end_points
  # POST /end_points.json
  def create
    @end_point = EndPoint.new(params[:end_point])

    respond_to do |format|
      if @end_point.save
        format.html { redirect_to @end_point, notice: 'End point was successfully created.' }
        format.json { render json: @end_point, status: :created, location: @end_point }
      else
        format.html { render action: "new" }
        format.json { render json: @end_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /end_points/1
  # PUT /end_points/1.json
  def update
    @end_point = EndPoint.find(params[:id])

    respond_to do |format|
      if @end_point.update_attributes(params[:end_point])
        format.html { redirect_to @end_point, notice: 'End point was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @end_point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /end_points/1
  # DELETE /end_points/1.json
  def destroy
    @end_point = EndPoint.find(params[:id])
    @end_point.destroy

    respond_to do |format|
      format.html { redirect_to end_points_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/discovery_helper.rb
module DiscoveryHelper
end

app/helpers/end_points_helper.rb
module EndPointsHelper
end

app/views/discovery/index.html.erb
<h1>Discovery</h1>

<p>Changeset: ...</p>
<p>Contact: For help or to report bugs please email...</p>
<p>Key Service: ...</p>

<br/>

<table>
  <tr>
    <th>Url</th>
    <th>Change set</th>
    <th>Specification</th>
    <th>Environment</th>
  </tr>

<% @end_points.each do |end_point| %>
  <tr>
    <td><%= link_to end_point.url, end_point_path(end_point) %></td>
    <td><%= end_point.change_set %></td>
    <td><%= end_point.specification %></td>
    <td><%= end_point.environment %></td>
  </tr>
<% end %>
</table>

app/views/end_points/_form.html.erb
<%= form_for(@end_point) do |f| %>
  <% if @end_point.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@end_point.errors.count, "error") %> prohibited this end_point from being saved:</h2>

      <ul>
      <% @end_point.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :change_set %><br />
    <%= f.text_field :change_set %>
  </div>
  <div class="field">
    <%= f.label :specification %><br />
    <%= f.text_field :specification %>
  </div>
  <div class="field">
    <%= f.label :environment %><br />
    <%= f.text_field :environment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/end_points/edit.html.erb
<h1>Editing end_point</h1>

<%= render 'form' %>

<%= link_to 'Show', @end_point %> |
<%= link_to 'Back', end_points_path %>

app/views/end_points/index.html.erb
<h1>Listing end_points</h1>

<table>
  <tr>
    <th>Url</th>
    <th>Change set</th>
    <th>Specification</th>
    <th>Environment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @end_points.each do |end_point| %>
  <tr>
    <td><%= end_point.url %></td>
    <td><%= end_point.change_set %></td>
    <td><%= end_point.specification %></td>
    <td><%= end_point.environment %></td>
    <td><%= link_to 'Show', end_point %></td>
    <td><%= link_to 'Edit', edit_end_point_path(end_point) %></td>
    <td><%= link_to 'Destroy', end_point, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New End point', new_end_point_path %>

app/views/end_points/new.html.erb
<h1>New end_point</h1>

<%= render 'form' %>

<%= link_to 'Back', end_points_path %>

app/views/end_points/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @end_point.url %>
</p>

<p>
  <b>Change set:</b>
  <%= @end_point.change_set %>
</p>

<p>
  <b>Specification:</b>
  <%= @end_point.specification %>
</p>

<p>
  <b>Environment:</b>
  <%= @end_point.environment %>
</p>


<%= link_to 'Edit', edit_end_point_path(@end_point) %> |
<%= link_to 'Back', end_points_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Open311Router</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>